export interface CountryEntry {
  code: string;
  dial: string;
  flag: string;
  name: string;
  minLen: number;
  maxLen: number;
}

export const COUNTRY_CODES: CountryEntry[] = [
  { code: 'US', dial: '+1', flag: '\uD83C\uDDFA\uD83C\uDDF8', name: 'United States', minLen: 10, maxLen: 10 },
  { code: 'CA', dial: '+1', flag: '\uD83C\uDDE8\uD83C\uDDE6', name: 'Canada', minLen: 10, maxLen: 10 },
  { code: 'GB', dial: '+44', flag: '\uD83C\uDDEC\uD83C\uDDE7', name: 'United Kingdom', minLen: 10, maxLen: 10 },
  { code: 'AF', dial: '+93', flag: '\uD83C\uDDE6\uD83C\uDDEB', name: 'Afghanistan', minLen: 9, maxLen: 9 },
  { code: 'AL', dial: '+355', flag: '\uD83C\uDDE6\uD83C\uDDF1', name: 'Albania', minLen: 8, maxLen: 9 },
  { code: 'DZ', dial: '+213', flag: '\uD83C\uDDE9\uD83C\uDDFF', name: 'Algeria', minLen: 9, maxLen: 9 },
  { code: 'AR', dial: '+54', flag: '\uD83C\uDDE6\uD83C\uDDF7', name: 'Argentina', minLen: 10, maxLen: 11 },
  { code: 'AU', dial: '+61', flag: '\uD83C\uDDE6\uD83C\uDDFA', name: 'Australia', minLen: 9, maxLen: 9 },
  { code: 'AT', dial: '+43', flag: '\uD83C\uDDE6\uD83C\uDDF9', name: 'Austria', minLen: 10, maxLen: 11 },
  { code: 'BD', dial: '+880', flag: '\uD83C\uDDE7\uD83C\uDDE9', name: 'Bangladesh', minLen: 10, maxLen: 10 },
  { code: 'BE', dial: '+32', flag: '\uD83C\uDDE7\uD83C\uDDEA', name: 'Belgium', minLen: 9, maxLen: 9 },
  { code: 'BR', dial: '+55', flag: '\uD83C\uDDE7\uD83C\uDDF7', name: 'Brazil', minLen: 10, maxLen: 11 },
  { code: 'BG', dial: '+359', flag: '\uD83C\uDDE7\uD83C\uDDEC', name: 'Bulgaria', minLen: 8, maxLen: 9 },
  { code: 'KH', dial: '+855', flag: '\uD83C\uDDF0\uD83C\uDDED', name: 'Cambodia', minLen: 8, maxLen: 9 },
  { code: 'CL', dial: '+56', flag: '\uD83C\uDDE8\uD83C\uDDF1', name: 'Chile', minLen: 9, maxLen: 9 },
  { code: 'CN', dial: '+86', flag: '\uD83C\uDDE8\uD83C\uDDF3', name: 'China', minLen: 11, maxLen: 11 },
  { code: 'CO', dial: '+57', flag: '\uD83C\uDDE8\uD83C\uDDF4', name: 'Colombia', minLen: 10, maxLen: 10 },
  { code: 'CR', dial: '+506', flag: '\uD83C\uDDE8\uD83C\uDDF7', name: 'Costa Rica', minLen: 8, maxLen: 8 },
  { code: 'HR', dial: '+385', flag: '\uD83C\uDDED\uD83C\uDDF7', name: 'Croatia', minLen: 8, maxLen: 9 },
  { code: 'CZ', dial: '+420', flag: '\uD83C\uDDE8\uD83C\uDDFF', name: 'Czech Republic', minLen: 9, maxLen: 9 },
  { code: 'DK', dial: '+45', flag: '\uD83C\uDDE9\uD83C\uDDF0', name: 'Denmark', minLen: 8, maxLen: 8 },
  { code: 'DO', dial: '+1', flag: '\uD83C\uDDE9\uD83C\uDDF4', name: 'Dominican Republic', minLen: 10, maxLen: 10 },
  { code: 'EC', dial: '+593', flag: '\uD83C\uDDEA\uD83C\uDDE8', name: 'Ecuador', minLen: 9, maxLen: 9 },
  { code: 'EG', dial: '+20', flag: '\uD83C\uDDEA\uD83C\uDDEC', name: 'Egypt', minLen: 10, maxLen: 10 },
  { code: 'FI', dial: '+358', flag: '\uD83C\uDDEB\uD83C\uDDEE', name: 'Finland', minLen: 9, maxLen: 10 },
  { code: 'FR', dial: '+33', flag: '\uD83C\uDDEB\uD83C\uDDF7', name: 'France', minLen: 9, maxLen: 9 },
  { code: 'DE', dial: '+49', flag: '\uD83C\uDDE9\uD83C\uDDEA', name: 'Germany', minLen: 10, maxLen: 11 },
  { code: 'GH', dial: '+233', flag: '\uD83C\uDDEC\uD83C\uDDED', name: 'Ghana', minLen: 9, maxLen: 9 },
  { code: 'GR', dial: '+30', flag: '\uD83C\uDDEC\uD83C\uDDF7', name: 'Greece', minLen: 10, maxLen: 10 },
  { code: 'GT', dial: '+502', flag: '\uD83C\uDDEC\uD83C\uDDF9', name: 'Guatemala', minLen: 8, maxLen: 8 },
  { code: 'HN', dial: '+504', flag: '\uD83C\uDDED\uD83C\uDDF3', name: 'Honduras', minLen: 8, maxLen: 8 },
  { code: 'HK', dial: '+852', flag: '\uD83C\uDDED\uD83C\uDDF0', name: 'Hong Kong', minLen: 8, maxLen: 8 },
  { code: 'HU', dial: '+36', flag: '\uD83C\uDDED\uD83C\uDDFA', name: 'Hungary', minLen: 9, maxLen: 9 },
  { code: 'IN', dial: '+91', flag: '\uD83C\uDDEE\uD83C\uDDF3', name: 'India', minLen: 10, maxLen: 10 },
  { code: 'ID', dial: '+62', flag: '\uD83C\uDDEE\uD83C\uDDE9', name: 'Indonesia', minLen: 10, maxLen: 12 },
  { code: 'IE', dial: '+353', flag: '\uD83C\uDDEE\uD83C\uDDEA', name: 'Ireland', minLen: 9, maxLen: 9 },
  { code: 'IL', dial: '+972', flag: '\uD83C\uDDEE\uD83C\uDDF1', name: 'Israel', minLen: 9, maxLen: 9 },
  { code: 'IT', dial: '+39', flag: '\uD83C\uDDEE\uD83C\uDDF9', name: 'Italy', minLen: 9, maxLen: 10 },
  { code: 'JM', dial: '+1', flag: '\uD83C\uDDEF\uD83C\uDDF2', name: 'Jamaica', minLen: 10, maxLen: 10 },
  { code: 'JP', dial: '+81', flag: '\uD83C\uDDEF\uD83C\uDDF5', name: 'Japan', minLen: 10, maxLen: 10 },
  { code: 'KE', dial: '+254', flag: '\uD83C\uDDF0\uD83C\uDDEA', name: 'Kenya', minLen: 9, maxLen: 9 },
  { code: 'MY', dial: '+60', flag: '\uD83C\uDDF2\uD83C\uDDFE', name: 'Malaysia', minLen: 9, maxLen: 10 },
  { code: 'MX', dial: '+52', flag: '\uD83C\uDDF2\uD83C\uDDFD', name: 'Mexico', minLen: 10, maxLen: 10 },
  { code: 'MA', dial: '+212', flag: '\uD83C\uDDF2\uD83C\uDDE6', name: 'Morocco', minLen: 9, maxLen: 9 },
  { code: 'NL', dial: '+31', flag: '\uD83C\uDDF3\uD83C\uDDF1', name: 'Netherlands', minLen: 9, maxLen: 9 },
  { code: 'NZ', dial: '+64', flag: '\uD83C\uDDF3\uD83C\uDDFF', name: 'New Zealand', minLen: 9, maxLen: 10 },
  { code: 'NG', dial: '+234', flag: '\uD83C\uDDF3\uD83C\uDDEC', name: 'Nigeria', minLen: 10, maxLen: 10 },
  { code: 'NO', dial: '+47', flag: '\uD83C\uDDF3\uD83C\uDDF4', name: 'Norway', minLen: 8, maxLen: 8 },
  { code: 'PK', dial: '+92', flag: '\uD83C\uDDF5\uD83C\uDDF0', name: 'Pakistan', minLen: 10, maxLen: 10 },
  { code: 'PA', dial: '+507', flag: '\uD83C\uDDF5\uD83C\uDDE6', name: 'Panama', minLen: 7, maxLen: 8 },
  { code: 'PE', dial: '+51', flag: '\uD83C\uDDF5\uD83C\uDDEA', name: 'Peru', minLen: 9, maxLen: 9 },
  { code: 'PH', dial: '+63', flag: '\uD83C\uDDF5\uD83C\uDDED', name: 'Philippines', minLen: 10, maxLen: 10 },
  { code: 'PL', dial: '+48', flag: '\uD83C\uDDF5\uD83C\uDDF1', name: 'Poland', minLen: 9, maxLen: 9 },
  { code: 'PT', dial: '+351', flag: '\uD83C\uDDF5\uD83C\uDDF9', name: 'Portugal', minLen: 9, maxLen: 9 },
  { code: 'PR', dial: '+1', flag: '\uD83C\uDDF5\uD83C\uDDF7', name: 'Puerto Rico', minLen: 10, maxLen: 10 },
  { code: 'RO', dial: '+40', flag: '\uD83C\uDDF7\uD83C\uDDF4', name: 'Romania', minLen: 9, maxLen: 9 },
  { code: 'RU', dial: '+7', flag: '\uD83C\uDDF7\uD83C\uDDFA', name: 'Russia', minLen: 10, maxLen: 10 },
  { code: 'SA', dial: '+966', flag: '\uD83C\uDDF8\uD83C\uDDE6', name: 'Saudi Arabia', minLen: 9, maxLen: 9 },
  { code: 'SG', dial: '+65', flag: '\uD83C\uDDF8\uD83C\uDDEC', name: 'Singapore', minLen: 8, maxLen: 8 },
  { code: 'ZA', dial: '+27', flag: '\uD83C\uDDFF\uD83C\uDDE6', name: 'South Africa', minLen: 9, maxLen: 9 },
  { code: 'KR', dial: '+82', flag: '\uD83C\uDDF0\uD83C\uDDF7', name: 'South Korea', minLen: 10, maxLen: 11 },
  { code: 'ES', dial: '+34', flag: '\uD83C\uDDEA\uD83C\uDDF8', name: 'Spain', minLen: 9, maxLen: 9 },
  { code: 'SE', dial: '+46', flag: '\uD83C\uDDF8\uD83C\uDDEA', name: 'Sweden', minLen: 9, maxLen: 10 },
  { code: 'CH', dial: '+41', flag: '\uD83C\uDDE8\uD83C\uDDED', name: 'Switzerland', minLen: 9, maxLen: 9 },
  { code: 'TW', dial: '+886', flag: '\uD83C\uDDF9\uD83C\uDDFC', name: 'Taiwan', minLen: 9, maxLen: 9 },
  { code: 'TH', dial: '+66', flag: '\uD83C\uDDF9\uD83C\uDDED', name: 'Thailand', minLen: 9, maxLen: 9 },
  { code: 'TR', dial: '+90', flag: '\uD83C\uDDF9\uD83C\uDDF7', name: 'Turkey', minLen: 10, maxLen: 10 },
  { code: 'UA', dial: '+380', flag: '\uD83C\uDDFA\uD83C\uDDE6', name: 'Ukraine', minLen: 9, maxLen: 9 },
  { code: 'AE', dial: '+971', flag: '\uD83C\uDDE6\uD83C\uDDEA', name: 'United Arab Emirates', minLen: 9, maxLen: 9 },
  { code: 'UY', dial: '+598', flag: '\uD83C\uDDFA\uD83C\uDDFE', name: 'Uruguay', minLen: 8, maxLen: 8 },
  { code: 'VE', dial: '+58', flag: '\uD83C\uDDFB\uD83C\uDDEA', name: 'Venezuela', minLen: 10, maxLen: 10 },
  { code: 'VN', dial: '+84', flag: '\uD83C\uDDFB\uD83C\uDDF3', name: 'Vietnam', minLen: 9, maxLen: 10 },
];
