import type { ChatEmbedConfig } from './types';

export const defaultConfig: ChatEmbedConfig = {
  title: 'Chat',
  customIcon: null,
  botIcon: {
    svgWidth: '24px',
    svgHeight: '24px',
    width: '24px',
    height: '24px',
    objectFit: 'contain',
    botAvatarUrl: null,
    botIconAvatarWidth: '40px',
    botIconAvatarHeight: '40px',
    botIconAvatarDisplay: 'flex',
  },
  botMessageWidth: '70%',
  userIcon: {
    userIconAvatarWidth: '40px',
    userIconAvatarHeight: '40px',
    userIconAvatarDisplay: 'flex',
    userMessageWidth: '70%',
  },
  theme: {
    primary: '#0078d4',
    userBubble: '#e6f0fa',
    botBubble: '#f1f1f1',
    userText: '#22223b',
    botText: '#4a4e69',
    background: '#fff',
    containerBg: '#ffffff',
    messagesBg: '#ffffff',
    inputContainerBg: '#ffffff',
    border: '#ccc',
    text: '#222',
    width: '100%',
    maxWidth: '350px',
    minWidth: '220px',
    borderRadius: '8px',
    fontFamily: 'sans-serif',
    zIndex: 9999,
    inputBg: '#fff',
    inputText: '#222',
    sendBtnBg: '#0078d4',
    sendBtnText: '#fff',
    sendBtnSvgColor: '#fff',
    sendBtnHover: '#005fa3',
    shadow: '0 2px 8px rgba(0,0,0,0.15)',
    salesRepBubble: '#f1f5f9',
    salesRepText: '#475569',
    salesRepAvatar: '#E4E7FC',
    userAvatar: '#8349ff',
    botAvatar: '#E4E7FC',
    userAvatarSvgColor: '#fff',
    botAvatarSvgColor: '#8349ff',
    salesRepAvatarSvgColor: '#8349ff',
    userAvatarBorder: 'none',
    botAvatarBorder: 'none',
    salesRepAvatarBorder: 'none',
    timestampColor: '#9ca3af',
    messageFontFamily: 'inherit',
    handoverNotificationBg: '#E4E7FC',
    handoverNotificationText: '#334155',
    handoverNotificationBorder: '#8349FF',
    closeBtnIconStyle: { display: '' },
    headerStyle: {
      backgroundColor: 'rgba(34, 34, 59, 0.95)',
      textColor: '#fff',
      fontWeight: '600',
      fontFamily: '',
      height: 'auto',
      padding: '32px',
      borderRadius: '12px',
      logoStyle: {
        logoUrl: '',
        logoWidth: '24px',
        logoHeight: '24px',
        borderRadius: '0',
      },
    },
  },
  leadCapture: true,
  quickQuestions: [],
  quickQuestionsPermanent: false,
  position: 'right',
  ngrok: false,
  isMobileDevice: false,
  mode: 'floating',
};
